version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:6.10-browsers
        environment:
           version_number: $CIRCLE_BRANCH
           build_number: $CIRCLE_BUILD_NUM
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      
      #- run: git clone https://github.com/project-sunbird/sunbird-content-plugins.git plugins -b $CIRCLE_BRANCH
      - run: sudo npm install -g bower@1.8.0 grunt-cli@1.2.0 gulp@3.9.1 codacy-coverage
      - run: npm install
      - run: cd app && bower cache clean --allow-root
      - run: cd app && bower install --force --allow-root
      - run: gulp clone-plugins
      - run: gulp packageCorePlugins
      - run: npm run plugin-build
      - run: npm run build
      - run: npm run test
      #
      
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules
      
                
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
